name: .NET CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore ZeroAllocReceiver.sln

    - name: Build (Release)
      run: dotnet build ZeroAllocReceiver.sln --configuration Release --no-restore

    - name: Run Unit Tests
      run: dotnet test ZeroAllocReceiver.sln --configuration Release --no-build --verbosity normal
